[package]
name = "hanoi-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1.0.5"
clap = { version = "4.4.5", features = ["derive"] }
serde_json = "1.0.107"
futures = "0.3.28"
rayon = "1.8.0"

[profile.profiling]
inherits = "release"
debug = true
